/**
* Konnex Addresses API
* An API that allows for creating, reading, updating and deleting of Konnex Object Address data.
*
* OpenAPI spec version: 1.0.0
* Contact: info@konnex-engine.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "AddressesApi.h"
#include "Helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::helpers;
using namespace org::openapitools::server::model;

AddressesApi::AddressesApi(std::shared_ptr<Pistache::Rest::Router> rtr) { 
    router = rtr;
};

void AddressesApi::init() {
    setupRoutes();
}

void AddressesApi::setupRoutes() {
    using namespace Pistache::Rest;

    Routes::Post(*router, base + "/:objectType/:objectID/addresses", Routes::bind(&AddressesApi::create_address_handler, this));
    Routes::Delete(*router, base + "/:objectType/:objectID/addresses/:addressID", Routes::bind(&AddressesApi::delete_address_handler, this));
    Routes::Get(*router, base + "/:objectType/:objectID/addresses/:addressID", Routes::bind(&AddressesApi::get_address_by_id_handler, this));
    Routes::Get(*router, base + "/:objectType/:objectID/addresses", Routes::bind(&AddressesApi::get_addresses_handler, this));
    Routes::Put(*router, base + "/:objectType/:objectID/addresses/:addressID", Routes::bind(&AddressesApi::update_address_handler, this));

    // Default handler, called when a route is not found
    router->addCustomHandler(Routes::bind(&AddressesApi::addresses_api_default_handler, this));
}

void AddressesApi::create_address_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto objectType = request.param(":objectType").as<std::string>();
    auto objectID = request.param(":objectID").as<int32_t>();
    
    try {
      this->create_address(objectType, objectID, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void AddressesApi::delete_address_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto objectType = request.param(":objectType").as<std::string>();
    auto objectID = request.param(":objectID").as<int32_t>();
    auto addressID = request.param(":addressID").as<int32_t>();
    
    try {
      this->delete_address(objectType, objectID, addressID, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void AddressesApi::get_address_by_id_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto objectType = request.param(":objectType").as<std::string>();
    auto objectID = request.param(":objectID").as<int32_t>();
    auto addressID = request.param(":addressID").as<int32_t>();
    
    try {
      this->get_address_by_id(objectType, objectID, addressID, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void AddressesApi::get_addresses_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto objectType = request.param(":objectType").as<std::string>();
    auto objectID = request.param(":objectID").as<int32_t>();
    
    // Getting the query params
    auto bodyLimitQuery = request.query().get("bodyLimit");
    Pistache::Optional<int32_t> bodyLimit;
    if(!bodyLimitQuery.isEmpty()){
        int32_t value;
        if(fromStringValue(bodyLimitQuery.get(), value)){
            bodyLimit = Pistache::Some(value);
        }
    }
    auto pageLimitQuery = request.query().get("pageLimit");
    Pistache::Optional<int32_t> pageLimit;
    if(!pageLimitQuery.isEmpty()){
        int32_t value;
        if(fromStringValue(pageLimitQuery.get(), value)){
            pageLimit = Pistache::Some(value);
        }
    }
    
    try {
      this->get_addresses(objectType, objectID, bodyLimit, pageLimit, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void AddressesApi::update_address_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto objectType = request.param(":objectType").as<std::string>();
    auto objectID = request.param(":objectID").as<int32_t>();
    auto addressID = request.param(":addressID").as<int32_t>();
    
    // Getting the body param
    
    Address body;
    
    try {
      nlohmann::json request_body = nlohmann::json::parse(request.body());
    
      // The conversion is done automatically by the json library
      body = request_body;
      this->update_address(objectType, objectID, addressID, body, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}

void AddressesApi::addresses_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    response.send(Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}
}
}
}

