/**
* Konnex Company API
* An API that allows for creating, reading, updating and deleting of Konnex User Company data.
*
* OpenAPI spec version: 1.0.0
* Contact: info@konnex-engine.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "CompaniesApi.h"
#include "Helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::helpers;
using namespace org::openapitools::server::model;

CompaniesApi::CompaniesApi(std::shared_ptr<Pistache::Rest::Router> rtr) { 
    router = rtr;
};

void CompaniesApi::init() {
    setupRoutes();
}

void CompaniesApi::setupRoutes() {
    using namespace Pistache::Rest;

    Routes::Post(*router, base + "/companies", Routes::bind(&CompaniesApi::create_company_handler, this));
    Routes::Delete(*router, base + "/companies/:companyID", Routes::bind(&CompaniesApi::delete_company_handler, this));
    Routes::Get(*router, base + "/companies", Routes::bind(&CompaniesApi::get_companies_handler, this));
    Routes::Get(*router, base + "/companies/:companyID", Routes::bind(&CompaniesApi::get_company_by_id_handler, this));
    Routes::Put(*router, base + "/companies/:companyID", Routes::bind(&CompaniesApi::update_company_handler, this));

    // Default handler, called when a route is not found
    router->addCustomHandler(Routes::bind(&CompaniesApi::companies_api_default_handler, this));
}

void CompaniesApi::create_company_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    try {
      this->create_company(request, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void CompaniesApi::delete_company_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto companyID = request.param(":companyID").as<int32_t>();
    
    try {
      this->delete_company(companyID, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void CompaniesApi::get_companies_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {

    // Getting the query params
    auto bodyLimitQuery = request.query().get("bodyLimit");
    Pistache::Optional<int32_t> bodyLimit;
    if(!bodyLimitQuery.isEmpty()){
        int32_t value;
        if(fromStringValue(bodyLimitQuery.get(), value)){
            bodyLimit = Pistache::Some(value);
        }
    }
    auto pageLimitQuery = request.query().get("pageLimit");
    Pistache::Optional<int32_t> pageLimit;
    if(!pageLimitQuery.isEmpty()){
        int32_t value;
        if(fromStringValue(pageLimitQuery.get(), value)){
            pageLimit = Pistache::Some(value);
        }
    }
    
    try {
      this->get_companies(bodyLimit, pageLimit, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void CompaniesApi::get_company_by_id_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto companyID = request.param(":companyID").as<int32_t>();
    
    try {
      this->get_company_by_id(companyID, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void CompaniesApi::update_company_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto companyID = request.param(":companyID").as<int32_t>();
    
    // Getting the body param
    std::vector<KeyValuePairs> keyValuePairs;
    
    try {
      nlohmann::json request_body = nlohmann::json::parse(request.body());
      keyValuePairs =   ArrayHelper::fromJson<KeyValuePairs>(request_body);
      this->update_company(companyID, keyValuePairs, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}

void CompaniesApi::companies_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    response.send(Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}
}
}
}

