/**
* Konnex User API
* An API that allows for creating, reading, updating and deleting of Konnex User data.
*
* OpenAPI spec version: 1.0.0
* Contact: info@konnex-engine.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "UsersApi.h"
#include "Helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::helpers;
using namespace org::openapitools::server::model;

UsersApi::UsersApi(std::shared_ptr<Pistache::Rest::Router> rtr) { 
    router = rtr;
};

void UsersApi::init() {
    setupRoutes();
}

void UsersApi::setupRoutes() {
    using namespace Pistache::Rest;

    Routes::Post(*router, base + "/users", Routes::bind(&UsersApi::create_user_handler, this));
    Routes::Delete(*router, base + "/users/:userID", Routes::bind(&UsersApi::delete_user_handler, this));
    Routes::Get(*router, base + "/users/:userID", Routes::bind(&UsersApi::get_user_by_id_handler, this));
    Routes::Get(*router, base + "/users", Routes::bind(&UsersApi::get_users_handler, this));
    Routes::Put(*router, base + "/users/:userID", Routes::bind(&UsersApi::update_user_handler, this));

    // Default handler, called when a route is not found
    router->addCustomHandler(Routes::bind(&UsersApi::users_api_default_handler, this));
}

void UsersApi::create_user_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    try {
      this->create_user(request, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void UsersApi::delete_user_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto userID = request.param(":userID").as<int32_t>();
    
    try {
      this->delete_user(userID, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void UsersApi::get_user_by_id_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto userID = request.param(":userID").as<int32_t>();
    
    try {
      this->get_user_by_id(userID, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void UsersApi::get_users_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {

    // Getting the query params
    auto bodyLimitQuery = request.query().get("bodyLimit");
    Pistache::Optional<int32_t> bodyLimit;
    if(!bodyLimitQuery.isEmpty()){
        int32_t value;
        if(fromStringValue(bodyLimitQuery.get(), value)){
            bodyLimit = Pistache::Some(value);
        }
    }
    auto pageLimitQuery = request.query().get("pageLimit");
    Pistache::Optional<int32_t> pageLimit;
    if(!pageLimitQuery.isEmpty()){
        int32_t value;
        if(fromStringValue(pageLimitQuery.get(), value)){
            pageLimit = Pistache::Some(value);
        }
    }
    
    try {
      this->get_users(bodyLimit, pageLimit, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void UsersApi::update_user_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto userID = request.param(":userID").as<int32_t>();
    
    // Getting the body param
    
    User user;
    
    try {
      nlohmann::json request_body = nlohmann::json::parse(request.body());
    
      user.fromJson(request_body);
    
      this->update_user(userID, user, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}

void UsersApi::users_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    response.send(Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}
}
}
}

