/**
* Konnex User API
* An API that allows for creating, reading, updating and deleting of Konnex User data.
*
* OpenAPI spec version: 1.0.0
* Contact: info@konnex-engine.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UsersApi.h
 *
 * 
 */

#ifndef UsersApi_H_
#define UsersApi_H_


#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>


#include "CreateUserForm_full_name.h"
#include "User.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class  UsersApi {
public:
    UsersApi(std::shared_ptr<Pistache::Rest::Router>);
    virtual ~UsersApi() {}
    void init();

    const std::string base = "/v1";

private:
    void setupRoutes();

    void create_user_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void delete_user_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void get_user_by_id_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void get_users_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void update_user_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void users_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    std::shared_ptr<Pistache::Rest::Router> router;

    /// <summary>
    /// Creates a new Konnex User
    /// </summary>
    /// <remarks>
    /// Creates a new Konnex User in the database.
    /// </remarks>
    virtual void create_user(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Delete user data.
    /// </summary>
    /// <remarks>
    /// Delete records for a specific Konnex User.
    /// </remarks>
    /// <param name="userID">The User ID for the specific user.</param>
    virtual void delete_user(const int32_t &userID, Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Retrieves data for a specific Konnex User
    /// </summary>
    /// <remarks>
    /// Obtain information for a specific user by user ID.
    /// </remarks>
    /// <param name="userID">The User ID for the specific user.</param>
    virtual void get_user_by_id(const int32_t &userID, Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Retrieves all available Konnex User data
    /// </summary>
    /// <remarks>
    /// Obtain information about Konnex users.
    /// </remarks>
    /// <param name="bodyLimit">The number of user records to return. (optional, default to 0)</param>
    /// <param name="pageLimit">The number of pages of user records to return. (optional, default to 0)</param>
    virtual void get_users(const Pistache::Optional<int32_t> &bodyLimit, const Pistache::Optional<int32_t> &pageLimit, Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Update user data.
    /// </summary>
    /// <remarks>
    /// Update records for a specific Konnex User.
    /// </remarks>
    /// <param name="userID">The User ID for the specific user.</param>
    /// <param name="user"> (optional)</param>
    virtual void update_user(const int32_t &userID, const User &user, Pistache::Http::ResponseWriter &response) = 0;

};

}
}
}
}

#endif /* UsersApi_H_ */

