/**
* Konnex Contact Details API
* An API that allows for creating, reading, updating and deleting of Konnex User Contact Details data.
*
* OpenAPI spec version: 1.0.0
* Contact: info@konnex-engine.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* ContactDetailsApiImpl.h
*
* 
*/

#ifndef CONTACT_DETAILS_API_IMPL_H_
#define CONTACT_DETAILS_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <ContactDetailsApi.h>

#include <pistache/optional.h>

#include "Contact.h"
#include "KeyValuePairs.h"
#include <string>
#include <vector>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class ContactDetailsApiImpl : public org::openapitools::server::api::ContactDetailsApi {
public:
    ContactDetailsApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~ContactDetailsApiImpl() {}

    void create_contact_details(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter &response);
    void delete_contact_details(const std::string &objectType, const int32_t &objectID, const int32_t &contactID, Pistache::Http::ResponseWriter &response);
    void get_contact_details(const std::string &objectType, const int32_t &objectID, const Pistache::Optional<int32_t> &bodyLimit, const Pistache::Optional<int32_t> &pageLimit, Pistache::Http::ResponseWriter &response);
    void get_contact_details_by_id(const std::string &objectType, const int32_t &objectID, const int32_t &contactID, Pistache::Http::ResponseWriter &response);
    void update_contact_details(const std::string &objectType, const int32_t &objectID, const int32_t &contactID, const std::vector<KeyValuePairs> &keyValuePairs, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif