/**
* Konnex User API
* An API that allows for creating, reading, updating and deleting of Konnex User data.
*
* OpenAPI spec version: 1.0.0
* Contact: info@konnex-engine.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* UsersApiImpl.h
*
* 
*/

#ifndef USERS_API_IMPL_H_
#define USERS_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <UsersApi.h>

#include <pistache/optional.h>

#include "CreateUserForm_full_name.h"
#include "User.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class UsersApiImpl : public org::openapitools::server::api::UsersApi {
public:
    UsersApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~UsersApiImpl() {}

    void create_user(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter &response);
    void delete_user(const int32_t &userID, Pistache::Http::ResponseWriter &response);
    void get_user_by_id(const int32_t &userID, Pistache::Http::ResponseWriter &response);
    void get_users(const Pistache::Optional<int32_t> &bodyLimit, const Pistache::Optional<int32_t> &pageLimit, Pistache::Http::ResponseWriter &response);
    void update_user(const int32_t &userID, const User &user, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif