/**
* Konnex Company API
* An API that allows for creating, reading, updating and deleting of Konnex User Company data.
*
* OpenAPI spec version: 1.0.0
* Contact: info@konnex-engine.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "CompanyName.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

CompanyName::CompanyName()
{
    m_Legal_name = "";
    m_Legal_nameIsSet = false;
    m_Trading_name = "";
    m_Trading_nameIsSet = false;
    
}

CompanyName::~CompanyName()
{
}

void CompanyName::validate()
{
    // TODO: implement validation
}

nlohmann::json CompanyName::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    if(m_Legal_nameIsSet)
    {
        val["legal name"] = ModelBase::toJson(m_Legal_name);
    }
    if(m_Trading_nameIsSet)
    {
        val["trading name"] = ModelBase::toJson(m_Trading_name);
    }
    

    return val;
}

void CompanyName::fromJson(const nlohmann::json& val)
{
    if(val.find("legal name") != val.end())
    {
        setLegalName(val.at("legal name"));
    }
    if(val.find("trading name") != val.end())
    {
        setTradingName(val.at("trading name"));
    }
    
}


std::string CompanyName::getLegalName() const
{
    return m_Legal_name;
}
void CompanyName::setLegalName(std::string const& value)
{
    m_Legal_name = value;
    m_Legal_nameIsSet = true;
}
bool CompanyName::legalNameIsSet() const
{
    return m_Legal_nameIsSet;
}
void CompanyName::unsetLegal_name()
{
    m_Legal_nameIsSet = false;
}
std::string CompanyName::getTradingName() const
{
    return m_Trading_name;
}
void CompanyName::setTradingName(std::string const& value)
{
    m_Trading_name = value;
    m_Trading_nameIsSet = true;
}
bool CompanyName::tradingNameIsSet() const
{
    return m_Trading_nameIsSet;
}
void CompanyName::unsetTrading_name()
{
    m_Trading_nameIsSet = false;
}

}
}
}
}

