/**
* Konnex Company API
* An API that allows for creating, reading, updating and deleting of Konnex User Company data.
*
* OpenAPI spec version: 1.0.0
* Contact: info@konnex-engine.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * CompanyName.h
 *
 * The name(s) of the Company
 */

#ifndef CompanyName_H_
#define CompanyName_H_


#include "ModelBase.h"

#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// The name(s) of the Company
/// </summary>
class  CompanyName
    : public ModelBase
{
public:
    CompanyName();
    virtual ~CompanyName();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// CompanyName members

    /// <summary>
    /// 
    /// </summary>
    std::string getLegalName() const;
    void setLegalName(std::string const& value);
    bool legalNameIsSet() const;
    void unsetLegal_name();
    /// <summary>
    /// 
    /// </summary>
    std::string getTradingName() const;
    void setTradingName(std::string const& value);
    bool tradingNameIsSet() const;
    void unsetTrading_name();

protected:
    std::string m_Legal_name;
    bool m_Legal_nameIsSet;
    std::string m_Trading_name;
    bool m_Trading_nameIsSet;
};

}
}
}
}

#endif /* CompanyName_H_ */
