/**
* Konnex Contact Details API
* An API that allows for creating, reading, updating and deleting of Konnex User Contact Details data.
*
* OpenAPI spec version: 1.0.0
* Contact: info@konnex-engine.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Contact.h
 *
 * Data model containing a single Contact Detail.
 */

#ifndef Contact_H_
#define Contact_H_


#include "ModelBase.h"

#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Data model containing a single Contact Detail.
/// </summary>
class  Contact
    : public ModelBase
{
public:
    Contact();
    virtual ~Contact();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// Contact members

    /// <summary>
    /// The type of contact details. Email, Telephone, Mobile, Fax, Home, Work, Business
    /// </summary>
    std::string getType() const;
    void setType(std::string const& value);
        /// <summary>
    /// The value of the contact detail
    /// </summary>
    std::string getValue() const;
    void setValue(std::string const& value);
        /// <summary>
    /// Is this the default contact detail
    /// </summary>
    bool isIsDefault() const;
    void setIsDefault(bool const value);
    bool isDefaultIsSet() const;
    void unsetIs_default();

protected:
    std::string m_Type;

    std::string m_Value;

    bool m_Is_default;
    bool m_Is_defaultIsSet;
};

}
}
}
}

#endif /* Contact_H_ */
