/**
* Konnex Addresses API
* An API that allows for creating, reading, updating and deleting of Konnex Object Address data.
*
* OpenAPI spec version: 1.0.0
* Contact: info@konnex-engine.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * CountyObject.h
 *
 * 
 */

#ifndef CountyObject_H_
#define CountyObject_H_


#include "ModelBase.h"

#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  CountyObject
    : public ModelBase
{
public:
    CountyObject();
    virtual ~CountyObject();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// CountyObject members

    /// <summary>
    /// 
    /// </summary>
    std::string getCode() const;
    void setCode(std::string const& value);
    bool codeIsSet() const;
    void unsetCode();
    /// <summary>
    /// 
    /// </summary>
    std::string getName() const;
    void setName(std::string const& value);
    bool nameIsSet() const;
    void unsetName();

protected:
    std::string m_Code;
    bool m_CodeIsSet;
    std::string m_Name;
    bool m_NameIsSet;
};

}
}
}
}

#endif /* CountyObject_H_ */
