/**
* Konnex Addresses API
* An API that allows for creating, reading, updating and deleting of Konnex Object Address data.
*
* OpenAPI spec version: 1.0.0
* Contact: info@konnex-engine.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "CountryObject.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

CountryObject::CountryObject()
{
    m_Code = "";
    m_Name = "";
    m_NameIsSet = false;
    
}

CountryObject::~CountryObject()
{
}

void CountryObject::validate()
{
    // TODO: implement validation
}

nlohmann::json CountryObject::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["code"] = ModelBase::toJson(m_Code);
    if(m_NameIsSet)
    {
        val["name"] = ModelBase::toJson(m_Name);
    }
    

    return val;
}

void CountryObject::fromJson(const nlohmann::json& val)
{
    setCode(val.at("code"));
    if(val.find("name") != val.end())
    {
        setName(val.at("name"));
    }
    
}


std::string CountryObject::getCode() const
{
    return m_Code;
}
void CountryObject::setCode(std::string const& value)
{
    m_Code = value;
    
}
std::string CountryObject::getName() const
{
    return m_Name;
}
void CountryObject::setName(std::string const& value)
{
    m_Name = value;
    m_NameIsSet = true;
}
bool CountryObject::nameIsSet() const
{
    return m_NameIsSet;
}
void CountryObject::unsetName()
{
    m_NameIsSet = false;
}

}
}
}
}

