/**
* Konnex Addresses API
* An API that allows for creating, reading, updating and deleting of Konnex Object Address data.
*
* OpenAPI spec version: 1.0.0
* Contact: info@konnex-engine.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "CountyObject.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

CountyObject::CountyObject()
{
    m_Code = "";
    m_CodeIsSet = false;
    m_Name = "";
    m_NameIsSet = false;
    
}

CountyObject::~CountyObject()
{
}

void CountyObject::validate()
{
    // TODO: implement validation
}

nlohmann::json CountyObject::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    if(m_CodeIsSet)
    {
        val["code"] = ModelBase::toJson(m_Code);
    }
    if(m_NameIsSet)
    {
        val["name"] = ModelBase::toJson(m_Name);
    }
    

    return val;
}

void CountyObject::fromJson(const nlohmann::json& val)
{
    if(val.find("code") != val.end())
    {
        setCode(val.at("code"));
    }
    if(val.find("name") != val.end())
    {
        setName(val.at("name"));
    }
    
}


std::string CountyObject::getCode() const
{
    return m_Code;
}
void CountyObject::setCode(std::string const& value)
{
    m_Code = value;
    m_CodeIsSet = true;
}
bool CountyObject::codeIsSet() const
{
    return m_CodeIsSet;
}
void CountyObject::unsetCode()
{
    m_CodeIsSet = false;
}
std::string CountyObject::getName() const
{
    return m_Name;
}
void CountyObject::setName(std::string const& value)
{
    m_Name = value;
    m_NameIsSet = true;
}
bool CountyObject::nameIsSet() const
{
    return m_NameIsSet;
}
void CountyObject::unsetName()
{
    m_NameIsSet = false;
}

}
}
}
}

