/**
* Konnex Company API
* An API that allows for creating, reading, updating and deleting of Konnex User Company data.
*
* OpenAPI spec version: 1.0.0
* Contact: info@konnex-engine.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "CreateCompanyForm.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

CreateCompanyForm::CreateCompanyForm()
{
    m_UserID = 0;
    m_NameIsSet = false;
    
}

CreateCompanyForm::~CreateCompanyForm()
{
}

void CreateCompanyForm::validate()
{
    // TODO: implement validation
}

nlohmann::json CreateCompanyForm::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["userID"] = m_UserID;
    if(m_NameIsSet)
    {
        val["name"] = ModelBase::toJson(m_Name);
    }
    

    return val;
}

void CreateCompanyForm::fromJson(const nlohmann::json& val)
{
    setUserID(val.at("userID"));
    if(val.find("name") != val.end())
    {
        if(!val["name"].is_null())
        {
            CompanyName newItem;
            newItem.fromJson(val["name"]);
            setName( newItem );
        }
        
    }
    
}


int32_t CreateCompanyForm::getUserID() const
{
    return m_UserID;
}
void CreateCompanyForm::setUserID(int32_t const value)
{
    m_UserID = value;
    
}
CompanyName CreateCompanyForm::getName() const
{
    return m_Name;
}
void CreateCompanyForm::setName(CompanyName const& value)
{
    m_Name = value;
    m_NameIsSet = true;
}
bool CreateCompanyForm::nameIsSet() const
{
    return m_NameIsSet;
}
void CreateCompanyForm::unsetName()
{
    m_NameIsSet = false;
}

}
}
}
}

