/**
* Konnex User API
* An API that allows for creating, reading, updating and deleting of Konnex User data.
*
* OpenAPI spec version: 1.0.0
* Contact: info@konnex-engine.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * CreateUserForm.h
 *
 * 
 */

#ifndef CreateUserForm_H_
#define CreateUserForm_H_


#include "ModelBase.h"

#include <string>
#include "CreateUserForm_full_name.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  CreateUserForm
    : public ModelBase
{
public:
    CreateUserForm();
    virtual ~CreateUserForm();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// CreateUserForm members

    /// <summary>
    /// 
    /// </summary>
    std::string getEmail() const;
    void setEmail(std::string const& value);
        /// <summary>
    /// 
    /// </summary>
    std::string getPassword() const;
    void setPassword(std::string const& value);
        /// <summary>
    /// 
    /// </summary>
    std::string getUsername() const;
    void setUsername(std::string const& value);
    bool usernameIsSet() const;
    void unsetUsername();
    /// <summary>
    /// 
    /// </summary>
    CreateUserForm_full_name getFullName() const;
    void setFullName(CreateUserForm_full_name const& value);
    bool fullNameIsSet() const;
    void unsetFull_name();

protected:
    std::string m_Email;

    std::string m_Password;

    std::string m_Username;
    bool m_UsernameIsSet;
    CreateUserForm_full_name m_Full_name;
    bool m_Full_nameIsSet;
};

}
}
}
}

#endif /* CreateUserForm_H_ */
