/**
* Konnex Addresses API
* An API that allows for creating, reading, updating and deleting of Konnex Object Address data.
*
* OpenAPI spec version: 1.0.0
* Contact: info@konnex-engine.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "CreateAddressForm.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

CreateAddressForm::CreateAddressForm()
{
    
}

CreateAddressForm::~CreateAddressForm()
{
}

void CreateAddressForm::validate()
{
    // TODO: implement validation
}

nlohmann::json CreateAddressForm::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    

    return val;
}

void CreateAddressForm::fromJson(const nlohmann::json& val)
{
    
}



}
}
}
}

