/**
* Konnex Company API
* An API that allows for creating, reading, updating and deleting of Konnex User Company data.
*
* OpenAPI spec version: 1.0.0
* Contact: info@konnex-engine.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * KeyValuePairs.h
 *
 * 
 */

#ifndef KeyValuePairs_H_
#define KeyValuePairs_H_


#include "ModelBase.h"

#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  KeyValuePairs
    : public ModelBase
{
public:
    KeyValuePairs();
    virtual ~KeyValuePairs();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// KeyValuePairs members

    /// <summary>
    /// 
    /// </summary>
    std::string getKey() const;
    void setKey(std::string const& value);
    bool keyIsSet() const;
    void unsetKey();
    /// <summary>
    /// 
    /// </summary>
    std::string getValue() const;
    void setValue(std::string const& value);
    bool valueIsSet() const;
    void unsetValue();

protected:
    std::string m_Key;
    bool m_KeyIsSet;
    std::string m_Value;
    bool m_ValueIsSet;
};

}
}
}
}

#endif /* KeyValuePairs_H_ */
